{% set name = "wagtailgridder" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtailgridder-{{ version }}.tar.gz
  sha256: a785bf6c3f2456fa5421296bb23fffa8584fd549ed81eec0437cad45e9311368

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67
    - setuptools-scm >=7
    - wheel
    - pip
  run:
    - python >=3.8
    - wagtail >=3

test:
  imports:
    - wagtailgridder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wharton/wagtailgridder
  summary: Dynamic, interactive grid layout for the Django CMS Wagtail.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
